name = "gvtech-design"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "apps/playground-web/dist-site"

[vars]
NODE_VERSION = "24"
APP_ENV = "production"

[env.preview]
name = "gvtech-design-preview"

[env.preview.vars]
NODE_VERSION = "24"
APP_ENV = "preview"

[env.production]
name = "gvtech-design"

[env.production.vars]
NODE_VERSION = "24"
APP_ENV = "production"
